### ISSUE TITLE
Loopback IP address configuration support

### ISSUE THREAD

**Issue by benagricola** [rackn/netwrangler#6]
As discussed with @VictorLowther in Slack, netwrangler currently avoids any configuration of loopback devices (e.g. `lo`), returning `Ethernet interface lo does not resolve to any interfaces` as this is explicitly excluded for being a "virtual" interface.

There is cases where configuring IP addresses on loopback is important during bootstrapping, for example when configuring servers running in a CLOS fabric where the servers' "unique" address is applied to loopback so it can be announced into the fabric.

It'd be good to support this use case, the reference netplan implementation appears to support address configuration on loopback as part of the `ethernets` config entry.

**Comment by sygibson** [comment]
Any environments doing routing protocols down to the host level (eg BGP: Calico/Contrail/BIRD/Quagga) usually configures Loopback network configuration as the source of the route advertisements ... that way advertisements are from a "host" and not a given interfaces, so multiple L3 paths are enabled for redundancy when upstream services fail.

**Comment by benagricola** [comment]
Yep, route-maps are usually installed to make the loopback address the source of any locally-originated traffic destined for routes learned over BGP.

Certain routing-on-host options allow for IP address configurations themselves (FRR / Cumulus Host Pack for example) so this isn't necessarily a blocker for pure L3 setups, but other tools (e.g. GoBGP or ExaBGP) are purely BGP speakers so are unable to do their own manipulation of interfaces.

**Comment by VictorLowther** [comment]
https://github.com/rackn/netwrangler/pull/8 will allow for this.
